<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <link name="base_link"></link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="base_footprint">
    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="0 0 0" />
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${chassis_height/2 + chassis_clearance}" />
            <geometry>
                <box size="${chassis_inner_length} ${chassis_inner_width} ${chassis_height}" />
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0 0 ${chassis_height/2 + chassis_clearance}" />
            <geometry>
                <box size="${chassis_inner_length} ${chassis_inner_width} ${chassis_height}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_inner_width * chassis_inner_length * metal_thickness * metal_density}"
            x="${chassis_inner_length}" y="${chassis_inner_width}" z="${chassis_height}">
            <origin xyz="0 0 ${chassis_height/2 + chassis_clearance}" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>


    <xacro:omni_wheel prefix="wheel3" parent="base_link">
        <origin
            xyz="-${chassis_inner_length/2 + wheel_thickness/2} ${chassis_inner_width/2 + wheel_thickness/2} ${wheel_radius/2}"
            rpy="0 ${pi/2} ${pi*3/4}" />

    </xacro:omni_wheel>

    <xacro:omni_wheel prefix="wheel2" parent="base_link">
        <origin
            xyz="${chassis_inner_length/2 + wheel_thickness/2} ${chassis_inner_width/2 + wheel_thickness/2} ${wheel_radius/2}"
            rpy="0 ${pi/2} ${pi/4}" />

    </xacro:omni_wheel>

    <xacro:omni_wheel prefix="wheel1" parent="base_link">
        <origin
            xyz="-${chassis_inner_length/2 + wheel_thickness/2} -${chassis_inner_width/2 + wheel_thickness/2} ${wheel_radius/2}"
            rpy="0 ${pi/2} ${-pi*3/4}" />

    </xacro:omni_wheel>

    <xacro:omni_wheel prefix="wheel0" parent="base_link">
        <origin
            xyz="${chassis_inner_length/2 + wheel_thickness/2} -${chassis_inner_width/2 + wheel_thickness/2} ${wheel_radius/2}"
            rpy="0 ${pi/2} ${-pi/4}" />

    </xacro:omni_wheel>

    <xacro:corner_frame nameprefix="frame_left_corner_top" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="-${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} ${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 0.785" />
    </xacro:corner_frame>

    <xacro:corner_frame nameprefix="frame_left_corner_bottom" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}" bz="${chassis_outer_thickness}">
        <origin
            xyz="-${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} ${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 0.785" />
    </xacro:corner_frame>


    <xacro:corner_frame nameprefix="frame_front_corner_top" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} ${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 -0.785" />
    </xacro:corner_frame>

    <xacro:corner_frame nameprefix="frame_front_corner_bottom" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}" bz="${chassis_outer_thickness}">
        <origin
            xyz="${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} ${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 -0.785" />
    </xacro:corner_frame>


    <xacro:corner_frame nameprefix="frame_right_corner_top" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} -${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 0.785" />
    </xacro:corner_frame>

    <xacro:corner_frame nameprefix="frame_right_corner_bottom" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}" bz="${chassis_outer_thickness}">
        <origin
            xyz="${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} -${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 0.785" />
    </xacro:corner_frame>


    <xacro:corner_frame nameprefix="frame_back_corner_top" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="-${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} -${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 -0.785" />
    </xacro:corner_frame>

    <xacro:corner_frame nameprefix="frame_back_corner_bottom" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}" bz="${chassis_outer_thickness}">
        <origin
            xyz="-${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} -${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 -0.785" />
    </xacro:corner_frame>


    <xacro:side_frame nameprefix="frame_left_front_side_top" bx="${chassis_outer_side}" by="${chassis_outer_thickness}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="0 ${chassis_width/2 - chassis_outer_thickness/2} ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>

    <xacro:side_frame nameprefix="frame_left_front_side_bottom" bx="${chassis_outer_side}"
        by="${chassis_outer_thickness}" bz="${chassis_outer_thickness}">
        <origin xyz="0 ${chassis_width/2 - chassis_outer_thickness/2} ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>


    <xacro:side_frame nameprefix="frame_front_right_side_top" bx="${chassis_outer_thickness}" by="${chassis_outer_side}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="${chassis_length/2 - chassis_outer_thickness/2} 0 ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>

    <xacro:side_frame nameprefix="frame_front_right_side_bottom" bx="${chassis_outer_thickness}"
        by="${chassis_outer_side}" bz="${chassis_outer_thickness}">
        <origin xyz="${chassis_length/2 - chassis_outer_thickness/2} 0 ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>


    <xacro:side_frame nameprefix="frame_right_back_side_top" bx="${chassis_outer_side}" by="${chassis_outer_thickness}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="0 -${chassis_width/2 - chassis_outer_thickness/2} ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>

    <xacro:side_frame nameprefix="frame_right_back_side_bottom" bx="${chassis_outer_side}"
        by="${chassis_outer_thickness}" bz="${chassis_outer_thickness}">
        <origin xyz="0 -${chassis_width/2 - chassis_outer_thickness/2} ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>


    <xacro:side_frame nameprefix="frame_back_left_side_top" bx="${chassis_outer_thickness}" by="${chassis_outer_side}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="-${chassis_length/2 - chassis_outer_thickness/2} 0 ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>

    <xacro:side_frame nameprefix="frame_back_left_side_bottom" bx="${chassis_outer_thickness}"
        by="${chassis_outer_side}" bz="${chassis_outer_thickness}">
        <origin
            xyz="-${chassis_length/2 - chassis_outer_thickness/2} 0 ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>

</robot>