<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- WHEEL PROPS -->
    <xacro:property name="wheel_radius" value="0.050" />
    <xacro:property name="wheel_thickness" value="0.038" />


    <!-- BASE LINK -->
    <link name="base_link"></link>


    <!-- CHASSIS LINK -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="0 0 0" />
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${chassis_height/2 + chassis_clearance}" />
            <geometry>
                <box size="${chassis_inner_length} ${chassis_inner_width} ${chassis_height}" />
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0 0 ${chassis_height/2 + chassis_clearance}" />
            <geometry>
                <box size="${chassis_inner_length} ${chassis_inner_width} ${chassis_height}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_inner_width * chassis_inner_length * metal_thickness * metal_density}"
            x="${chassis_inner_length}" y="${chassis_inner_width}" z="${chassis_height}">
            <origin xyz="0 0 ${chassis_height/2 + chassis_clearance}" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>


    <!-- WHEELS -->
    <!-- left wheel -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <origin
            xyz="-${chassis_inner_length/2 + wheel_thickness/2} ${chassis_inner_width/2 + wheel_thickness/2} ${wheel_radius/2}"
            rpy="-${pi/2} 0 0.785" />
        <axis xyz="0 0 -1" />
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder
            mass="1.0" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- front wheel -->
    <joint name="front_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_wheel" />
        <origin
            xyz="${chassis_inner_length/2 + wheel_thickness/2} ${chassis_inner_width/2 + wheel_thickness/2} ${wheel_radius/2}"
            rpy="-${pi/2} 0 -0.785" />
        <axis xyz="0 0 -1" />
    </joint>

    <link name="front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="front_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- right wheel -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <origin
            xyz="${chassis_inner_length/2 + wheel_thickness/2} -${chassis_inner_width/2 + wheel_thickness/2} ${wheel_radius/2}"
            rpy="${pi/2} ${pi} 0.785" />
        <axis xyz="0 0 -1" />
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- back wheel -->
    <joint name="back_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_wheel" />
        <origin
            xyz="-${chassis_inner_length/2 + wheel_thickness/2} -${chassis_inner_width/2 + wheel_thickness/2} ${wheel_radius/2}"
            rpy="${pi/2} ${pi} -0.785" />
        <axis xyz="0 0 -1" />
    </joint>

    <link name="back_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="back_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- FRAME -->
    <!-- CORNERS -->
    <!-- left corner -->
    <xacro:corner_frame nameprefix="frame_left_corner_top" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="-${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} ${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 0.785" />
    </xacro:corner_frame>

    <xacro:corner_frame nameprefix="frame_left_corner_bottom" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}" bz="${chassis_outer_thickness}">
        <origin
            xyz="-${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} ${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 0.785" />
    </xacro:corner_frame>

    <!-- front corner -->
    <xacro:corner_frame nameprefix="frame_front_corner_top" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} ${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 -0.785" />
    </xacro:corner_frame>

    <xacro:corner_frame nameprefix="frame_front_corner_bottom" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}" bz="${chassis_outer_thickness}">
        <origin
            xyz="${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} ${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 -0.785" />
    </xacro:corner_frame>

    <!-- right corner -->
    <xacro:corner_frame nameprefix="frame_right_corner_top" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} -${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 0.785" />
    </xacro:corner_frame>

    <xacro:corner_frame nameprefix="frame_right_corner_bottom" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}" bz="${chassis_outer_thickness}">
        <origin
            xyz="${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} -${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 0.785" />
    </xacro:corner_frame>

    <!-- back corner -->
    <xacro:corner_frame nameprefix="frame_back_corner_top" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="-${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} -${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 -0.785" />
    </xacro:corner_frame>

    <xacro:corner_frame nameprefix="frame_back_corner_bottom" parent="base_link" bx="${chassis_outer_corner}"
        by="${chassis_outer_thickness}" bz="${chassis_outer_thickness}">
        <origin
            xyz="-${chassis_length/2 - chassis_empty_space_length/2 + chassis_outer_thickness*135/360} -${chassis_width/2 - chassis_empty_space_width/2 + chassis_outer_thickness*135/360} ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 -0.785" />
    </xacro:corner_frame>


    <!-- SIDES -->
    <!-- left-front side -->
    <xacro:side_frame nameprefix="frame_left_front_side_top" bx="${chassis_outer_side}" by="${chassis_outer_thickness}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="0 ${chassis_width/2 - chassis_outer_thickness/2} ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>

    <xacro:side_frame nameprefix="frame_left_front_side_bottom" bx="${chassis_outer_side}"
        by="${chassis_outer_thickness}" bz="${chassis_outer_thickness}">
        <origin xyz="0 ${chassis_width/2 - chassis_outer_thickness/2} ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>

    <!-- front-right side -->
    <xacro:side_frame nameprefix="frame_front_right_side_top" bx="${chassis_outer_thickness}" by="${chassis_outer_side}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="${chassis_length/2 - chassis_outer_thickness/2} 0 ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>

    <xacro:side_frame nameprefix="frame_front_right_side_bottom" bx="${chassis_outer_thickness}"
        by="${chassis_outer_side}" bz="${chassis_outer_thickness}">
        <origin xyz="${chassis_length/2 - chassis_outer_thickness/2} 0 ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>

    <!-- right-back side -->
    <xacro:side_frame nameprefix="frame_right_back_side_top" bx="${chassis_outer_side}" by="${chassis_outer_thickness}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="0 -${chassis_width/2 - chassis_outer_thickness/2} ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>

    <xacro:side_frame nameprefix="frame_right_back_side_bottom" bx="${chassis_outer_side}"
        by="${chassis_outer_thickness}" bz="${chassis_outer_thickness}">
        <origin xyz="0 -${chassis_width/2 - chassis_outer_thickness/2} ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>

    <!-- back-left side -->
    <xacro:side_frame nameprefix="frame_back_left_side_top" bx="${chassis_outer_thickness}" by="${chassis_outer_side}"
        bz="${chassis_outer_thickness}">
        <origin
            xyz="-${chassis_length/2 - chassis_outer_thickness/2} 0 ${chassis_height + chassis_clearance - chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>

    <xacro:side_frame nameprefix="frame_back_left_side_bottom" bx="${chassis_outer_thickness}"
        by="${chassis_outer_side}" bz="${chassis_outer_thickness}">
        <origin
            xyz="-${chassis_length/2 - chassis_outer_thickness/2} 0 ${chassis_clearance + chassis_outer_thickness/2}"
            rpy="0 0 0" />
    </xacro:side_frame>

</robot>