<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <joint name="level_1_center_joint" type="fixed">
        <parent link="base_link" />
        <child link="level_1_center_link" />
        <origin
            xyz="${level_1_center_x} ${level_1_center_y} ${level_1_center_z}"
            ryp="0 0 0" />
    </joint>

    <link name="level_1_center_link">
    </link>


    <xacro:lidar nameprefix="laser"
        parent="level_1_center_link"
        length="${lidar_length}"
        radius="${lidar_radius}"
        mass="${lidar_weight}">
        <origin xyz="0 0 ${lidar_length/2}" rpy="0 0 0" />
        <frame_name>laser_frame</frame_name>
    </xacro:lidar>


    <xacro:base_plate nameprefix="level_1_base_plate_x"
        parent="level_1_center_link"
        bx="${level_1_base_length}"
        by="${chassis_inner_width}"
        bz="${metal_thickness}">
        <origin xyz="0 0 ${-metal_thickness/2}"
            rpy="0 0 0" />
    </xacro:base_plate>

    <xacro:base_plate nameprefix="level_1_base_plate_y"
        parent="level_1_center_link"
        bx="${chassis_inner_length}"
        by="${level_1_base_width}"
        bz="${metal_thickness}">
        <origin xyz="0 0 ${-metal_thickness/2}"
            rpy="0 0 0" />
    </xacro:base_plate>


    <xacro:corner_frame nameprefix="l1_frame_left_corner"
        parent="level_1_center_link"
        bx="${level_1_corner_length}"
        by="${level_1_corner_width}"
        bz="${metal_thickness}">
        <origin
            xyz="-${level_1_base_length/2 - level_1_empty_space_length/2 - chassis_outer_thickness - level_1_corner_length/2 + level_1_corner_length*135/360} ${level_1_base_width/2 - level_1_empty_space_width/2 - chassis_outer_thickness - level_1_corner_width/2 + level_1_corner_width*135/360} ${-metal_thickness/2}"
            rpy="0 0 0.785" />
    </xacro:corner_frame>


    <xacro:corner_frame nameprefix="l1_frame_front_corner"
        parent="level_1_center_link"
        bx="${level_1_corner_length}"
        by="${level_1_corner_width}"
        bz="${metal_thickness}">
        <origin
            xyz="${level_1_base_length/2 - level_1_empty_space_length/2 - chassis_outer_thickness - level_1_corner_length/2 + level_1_corner_length*135/360} ${level_1_base_width/2 - level_1_empty_space_width/2 - chassis_outer_thickness - level_1_corner_width/2 + level_1_corner_width*135/360} ${-metal_thickness/2}"
            rpy="0 0 -0.785" />
    </xacro:corner_frame>


    <xacro:corner_frame nameprefix="l1_frame_right_corner"
        parent="level_1_center_link"
        bx="${level_1_corner_length}"
        by="${level_1_corner_width}"
        bz="${metal_thickness}">
        <origin
            xyz="${level_1_base_length/2 - level_1_empty_space_length/2 - chassis_outer_thickness - level_1_corner_length/2 + level_1_corner_length*135/360} -${level_1_base_width/2 - level_1_empty_space_width/2 - chassis_outer_thickness - level_1_corner_width/2 + level_1_corner_width*135/360} ${-metal_thickness/2}"
            rpy="0 0 0.785" />
    </xacro:corner_frame>


    <xacro:corner_frame nameprefix="l1_frame_back_corner"
        parent="level_1_center_link"
        bx="${level_1_corner_length}"
        by="${level_1_corner_width}"
        bz="${metal_thickness}">
        <origin
            xyz="-${level_1_base_length/2 - level_1_empty_space_length/2 - chassis_outer_thickness - level_1_corner_length/2 + level_1_corner_length*135/360} -${level_1_base_width/2 - level_1_empty_space_width/2 - chassis_outer_thickness - level_1_corner_width/2 + level_1_corner_width*135/360} ${-metal_thickness/2}"
            rpy="0 0 -0.785" />
    </xacro:corner_frame>


    <xacro:support_cylinder nameprefix="l1_front_left_support_cylinder"
        parent="level_2_center_link"
        length="${level_1_support_height}"
        radius="${level_1_support_radius}">
        <origin
            xyz="${level_2_base_length/2 - level_2_support_displacement_x} ${level_2_base_width/2 - level_2_support_displacement_y} ${-level_1_support_height/2 - metal_thickness}"
            rpy="0 0 0" />
    </xacro:support_cylinder>

    <xacro:support_cylinder nameprefix="l1_front_right_support_cylinder"
        parent="level_2_center_link"
        length="${level_1_support_height}"
        radius="${level_1_support_radius}">
        <origin
            xyz="${level_2_base_length/2 - level_2_support_displacement_x} ${-level_2_base_width/2 + level_2_support_displacement_y} ${-level_1_support_height/2 - metal_thickness}"
            rpy="0 0 0" />
    </xacro:support_cylinder>

    <xacro:support_cylinder nameprefix="l1_back_right_support_cylinder"
        parent="level_2_center_link"
        length="${level_1_support_height}"
        radius="${level_1_support_radius}">
        <origin
            xyz="${-level_2_base_length/2 + level_2_support_displacement_x} ${-level_2_base_width/2 + level_2_support_displacement_y} ${-level_1_support_height/2 - metal_thickness}"
            rpy="0 0 0" />
    </xacro:support_cylinder>

    <xacro:support_cylinder nameprefix="l1_back_left_support_cylinder"
        parent="level_2_center_link"
        length="${level_1_support_height}"
        radius="${level_1_support_radius}">
        <origin
            xyz="${-level_2_base_length/2 + level_2_support_displacement_x} ${level_2_base_width/2 - level_2_support_displacement_y} ${-level_1_support_height/2 - metal_thickness}"
            rpy="0 0 0" />
    </xacro:support_cylinder>

</robot>