<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- BASE CORNER -->
    <xacro:macro name="corner_frame" params="nameprefix bx by bz *origin">
        <joint name="${nameprefix}_joint" type="fixed">
            <parent link="base_link" />
            <child link="${nameprefix}" />
            <xacro:insert_block name="origin" />
        </joint>

        <link name="${nameprefix}">
            <visual>
                <geometry>
                    <box size="${bx} ${by} ${bz}" />
                </geometry>
                <material name="white" />
            </visual>
            <collision>
                <geometry>
                    <box size="${bx} ${by} ${bz}" />
                </geometry>
            </collision>
            <xacro:inertial_box
                mass="${bx * by * metal_thickness * 4 * metal_density}"
                x="${bx}" y="${by}"
                z="${bz}">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:inertial_box>
        </link>

        <gazebo reference="${nameprefix}">
            <material>Gazebo/White</material>
        </gazebo>
    </xacro:macro>

    <!-- BASE SIDE -->
    <xacro:macro name="side_frame" params="nameprefix bx by bz *origin">
        <joint name="${nameprefix}_joint" type="fixed">
            <parent link="base_link" />
            <child link="${nameprefix}" />
            <xacro:insert_block name="origin" />
        </joint>

        <link name="${nameprefix}">
            <visual>
                <geometry>
                    <box size="${bx} ${by} ${bz}" />
                </geometry>
                <material name="white" />
            </visual>
            <collision>
                <geometry>
                    <box size="${bx} ${by} ${bz}" />
                </geometry>
            </collision>
            <xacro:inertial_box
                mass="${bx * by * metal_thickness * 4 * metal_density}"
                x="${bx}" y="${by}"
                z="${bz}">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:inertial_box>
        </link>

        <gazebo reference="${nameprefix}">
            <material>Gazebo/White</material>
        </gazebo>
    </xacro:macro>

    <!-- SUPPORT CYLINDER -->
    <xacro:macro name="support_cylinder" params="nameprefix length radius *origin">
        <joint name="${nameprefix}_joint" type="fixed">
            <parent link="base_link" />
            <child link="${nameprefix}" />
            <xacro:insert_block name="origin" />
        </joint>

        <link name="${nameprefix}">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <material name="white" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
            </collision>
            <xacro:inertial_cylinder
                mass="${2 * pi * radius * length * metal_thickness * metal_density}"
                radius="${radius}" length="${length}">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:inertial_cylinder>
        </link>

        <gazebo reference="${nameprefix}">
            <material>Gazebo/Grey</material>
        </gazebo>
    </xacro:macro>

    <!-- BASE PLATE -->
    <xacro:macro name="base_plate" params="nameprefix bx by bz *origin">
        <joint name="${nameprefix}_joint" type="fixed">
            <parent link="base_link" />
            <child link="${nameprefix}" />
            <xacro:insert_block name="origin" />
        </joint>

        <link name="${nameprefix}">
            <visual>
                <geometry>
                    <box size="${bx} ${by} ${bz}" />
                </geometry>
                <material name="white_transparent" />
            </visual>
            <collision>
                <geometry>
                    <box size="${bx} ${by} ${bz}" />
                </geometry>
            </collision>
            <xacro:inertial_box
                mass="${bx * by * metal_thickness * 4 * metal_density}"
                x="${bx}" y="${by}"
                z="${bz}">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:inertial_box>
        </link>

        <gazebo reference="${nameprefix}">
            <material>Gazebo/White</material>
        </gazebo>
    </xacro:macro>
</robot>