<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- INCLUDE -->
    <xacro:include filename="inertial_macros.xacro" />
    <xacro:include filename="materials.xacro" />

    <!-- ROBOT PROPERTIES -->
    <xacro:property name="chassis_length" value="0.5" />
    <xacro:property name="chassis_width" value="0.5" />
    <xacro:property name="chassis_height" value="0.5" />

    <!-- BASE LINK -->
    <link name="base_link"></link>

    <!-- CHASSIS LINK -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="0 0 0" />
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
            <geometry>
                <box size="{chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="1.0" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

</robot>