<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- CAMERA -->

    <!-- MIC -->

    <!-- DISPLAY -->

    <!-- STOP BUTTON -->

    <!-- BASE PLATE -->
    <xacro:base_plate nameprefix="level_3_base_plate" bx="${level_3_base_length}" by="${level_3_base_width}"
        bz="${metal_thickness}">
        <origin
            xyz="-${chassis_length/2 - level_3_base_length/2 - level_3_length_displacement} 0 ${level_3_height_displacement + metal_thickness/2}"
            rpy="0 0 0" />
    </xacro:base_plate>

</robot>